dat1<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",stringsAsFactors = FALSE)
dat2<-subset(dat1,(dat1$Date=="1/2/2007")|(dat1$Date=="2/2/2007"))
dat2$Time<-strptime(paste(dat2$Date,dat2$Time),"%d/%m/%Y %H:%M:%S")
dat2$Date<-as.Date.character(dat2$Date,"%d/%m/%Y")
par(mar=c(2,4,1,1),mfrow=c(1,1))
plot(dat2$Time,dat2$Sub_metering_1,ylab="Energy sub metering",type="n")
points(dat2$Time,dat2$Sub_metering_1,type="l")
points(dat2$Time,dat2$Sub_metering_2,type="l",col="red")
points(dat2$Time,dat2$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,cex=0.5)
dev.copy(png,"plot3.png")
dev.off()